from pymongo import MongoClient
from dotenv import load_dotenv
from os import environ
from pprint import pprint
from bson.objectid import ObjectId
load_dotenv()

key = environ['MONGODB_CONNECTION_STRING']

client = MongoClient(key)
db = client.wcoding

doc = {
    'name': 'Joseph Sungpil Choi',
    'message': 'This is a message from Jamsil'
}

# insert a single document into the collection called "test"
# db.test.insert_one(doc)

# find a SINGLE document from our collection
# _id is auto-generated by PyMongo and is unique to every document
# doc = db.test.find_one({ 'name': 'Joseph Sungpil Choi' })
# doc = db.test.find_one({'_id': ObjectId('61b9d7180d4cba853774cd5a')})
# pprint(doc)

# finding multiple documents from our collection 
# specify the query in the first dictionary argument
# docs = db.test.find({'name': 'Tierra Thompson'})
# for doc in docs:
#     pprint(doc)

# some example ObjectIds 
# 61b9d713d17b5b25c51f8cdf
# 61b9d720947e6fdaf0b42916
# 61b9de1cf67b9d185fa55635
# 61beb27e2d298a9f6b124b43

#db.test.update_one(
#    {
#        '_id': ObjectId('61b9d713d17b5b25c51f8cdf')
#    }, # how do we know which document to update?
#    {
#        '$set': {
#            'name': 'Jim Jones',
#            'message': 'Goodbye!!!!!',
#            'age': 25,
#            'hobbies': ['Basketball', 'Pokemon', 'Marvel'],
#        }
#    }, # how to actually update that document
#)
#doc = db.test.find_one({'_id': ObjectId('61b9d713d17b5b25c51f8cdf')})
#pprint(doc)

# example of deleting one document from the database
#res = db.test.delete_one({'_id': ObjectId('61beb59c87e1d4da77106d81')})
#print(res.acknowledged)
#print(res.deleted_count)
